# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]
  workflow_dispatch:
    

# Your workflows jobs.
jobs:
    Build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.10]

      steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
