# Your workflow name.
name: Ml-CI-CT-CD

on:
  push:
    branches: [master]
  workflow_dispatch:
    

# Your workflows jobs.
jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}